### PR TITLE
Pulling data from local json files.

### PR DESCRIPTION
**Pull request by phil-plencner-hl**
**Pulling data from local json files.**
* * *
# What does this Pull Request do?
This replaces the Google Doc with files in a folder in the container (`/app/static/files`).

# How should this be tested?

A description of what steps someone could take to:
* Take the .zip file Maura C. provided and unzip it in the `/app/static/files` folder. (You really only need the two .json files: `drs_migration.json` and `failed_file.json`)
* Restart the container. You should see the charts show up properly.
* If you view the source, you should see the JSON data it is using in between `<script>` tags on lines 16-19.
* You can update data in the files, and you should see it reflected on the site if you refresh.

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? No 
- integration tests? No

# Interested parties
@dl-maura @mferrarini @enriquediaz @awoods

### CODE REVIEW

**Comment by mferrarini** [comment]
tested this out locally and it's working for me. i removed a bunch of verify_failed object ids and messed around with the last day’s data that appears in the table and saw both of these changes reflected when refreshing the page!

**Comment by awoods** [comment]
Can I get a reminder on how to test the app in general? The following command succeeds:
```
docker-compose -f docker-compose-local.yml up --build --force-recreate
```
..but which endpoint should I hit to see the app?

**Comment by phil-plencner-hl** [comment]
> 
> 
> Can I get a reminder on how to test the app in general? The following command succeeds:
> 
> ```
> docker-compose -f docker-compose-local.yml up --build --force-recreate
> ```
> 
> ..but which endpoint should I hit to see the app?

Hi @awoods,

I Slacked you the data file and where to put it. (app/static/files). Once you do that you should be able to see the charts here:
https://localhost:3001/migrationstatus

**Review by dl-maura — APPROVED** [review]
Seems to work for me!

**Review by awoods — APPROVED** [review]

**Pull request merged**
